/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"

	drs_support "github.com/michael-conway/irods-go-drs/drs-support"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/irods-drs"
	//
	sw "github.com/michael-conway/irods-go-drs/internal"
)

func timeoutSecondsOrDefault(value int, fallback time.Duration) time.Duration {
	if value <= 0 {
		return fallback
	}
	return time.Duration(value) * time.Second
}

func main() {
	cfg, err := drs_support.ReadDrsConfig("", "", nil)
	if err != nil {
		log.Fatalf("read drs config: %v", err)
	}

	sampler, err := sw.NewServiceInfoSampler(cfg)
	if err != nil {
		log.Fatalf("create service info sampler: %v", err)
	}

	sw.SetDefaultServiceInfoSampler(sampler)

	log.Print("Running initial service info sampler query")
	if err := sampler.Start(context.Background()); err != nil {
		log.Fatalf("start service info sampler: %v", err)
	}

	log.Printf("Server started on :%d", cfg.DrsListenPort)

	router := sw.NewRouter()

	server := &http.Server{
		Addr:              fmt.Sprintf(":%d", cfg.DrsListenPort),
		Handler:           router,
		ReadTimeout:       timeoutSecondsOrDefault(cfg.HTTPReadTimeoutSeconds, 30*time.Second),
		ReadHeaderTimeout: timeoutSecondsOrDefault(cfg.HTTPReadHeaderTimeoutSeconds, 30*time.Second),
		WriteTimeout:      timeoutSecondsOrDefault(cfg.HTTPWriteTimeoutSeconds, 60*time.Second),
		IdleTimeout:       timeoutSecondsOrDefault(cfg.HTTPIdleTimeoutSeconds, 120*time.Second),
	}

	log.Fatal(server.ListenAndServe())
}
