DrsLogLevel: info
DrsListenPort: 8888

IrodsHost: localhost
IrodsPort: 1247
IrodsZone: tempZone
IrodsAdminUser: rods
IrodsAdminPassword: rods
IrodsPrimaryTestUser: test1
IrodsPrimaryTestPassword: test
IrodsSecondaryTestUser: test2
IrodsSecondaryTestPassword: test
IrodsAuthScheme: native
IrodsAdminLoginType: native
IrodsNegotiationPolicy: CS_NEG_DONT_CARE
IrodsDefaultResource: providerResc

OidcUrl: https://localhost:8443
OidcClientId: irods-go-drs
OidcClientSecret: change-me
OidcRealm: drs
OidcScope: openid profile email
OidcInsecureSkipVerify: true

DefaultTicketLifetimeMinutes: 720
DefaultTicketUseLimit: 50

IrodsAccessMethodSupported: true
FileAccessMethodSupported: false

HttpsAccessMethodSupported: true
HttpsAccessUseTicket: true
HttpsAccessImplementation: irods-go-rest
HttpsAccessMethodBaseURL: http://127.0.0.1:8080/api/v1/path/contents?irods_path=
HttpsResourceAffinity:
  - Host: http://127.0.0.1:8080
    Resources:
      - providerResc
  - Host: http://127.0.0.1:8082
    Resources:
      - resourceResc

S3AccessMethodSupported: true
S3AccessMethodBaseURL: s3://
S3ResourceAffinity:
  - Host: http://127.0.0.1:9001
    Resources:
      - providerResc
  - Host: http://127.0.0.1:9002
    Resources:
      - resourceResc
