DrsIdAvuValue: drs-id
DrsAvuUnit: irods:drs
DrsLogLevel: info
IrodsHost:
IrodsPort:
IrodsZone:
IrodsDrsAdminUser:
IrodsDrsAdminPassword:
IrodsDrsAdminLoginType:
IrodsAuthScheme:
IrodsNegotiationPolicy: native
IrodsDefaultResource:

  