DrsIdAvuValue: drs-id
DrsAvuUnit: irods:drs
DrsLogLevel: info
IrodsHost:
IrodsPort:
IrodsZone:
IrodsDrsAdminUser:
IrodsDrsAdminPassword:
IrodsDrsAdminPasswordFile:
IrodsDrsAdminLoginType:
IrodsAuthScheme:
IrodsNegotiationPolicy: native
IrodsDefaultResource:
OidcUrl:
OidcClientId:
OidcClientSecret:
OidcClientSecretFile:
OidcRealm:
OidcScope: openid profile email
  
