DrsIdAvuValue: drs-id
DrsAvuUnit: irods:drs
DrsLogLevel: info
DrsListenPort: 8080
ServiceInfoSampleIntervalMinutes: 5
ServiceInfoFilePath: service-info.json
HTTPAccessBaseURL: http://localhost:8080
IRODSAccessHost: localhost
IRODSAccessPort: 1247
LocalAccessRootPath:
S3AccessEndpoint:
IrodsHost: localhost
IrodsPort: 1247
IrodsZone: tempZone
IrodsAdminUser: rods
IrodsAdminPasswordFile: ./resources/irods-admin-password.txt
IrodsPrimaryTestUser: test1
IrodsPrimaryTestPassword: test1
IrodsSecondaryTestUser: test2ob
IrodsSecondaryTestPassword: test2
IrodsAuthScheme: native
IrodsNegotiationPolicy: native
IrodsDefaultResource:
OidcUrl: https://localhost:8443
OidcClientId: drs-api
OidcClientSecretFile: ./resources/oidc-client-secret.txt
OidcRealm: drs
OidcScope: openid profile email
OidcInsecureSkipVerify: true

IrodsAccessMethodSupported: false
FileAccessMethodSupported: false
HttpsAccessMethodSupported: true
HttpsAccessMethodBaseURL: http://localhost:8080/api/v1/path/contents?irods_path=
HttpsAccessUseTicket: true

