/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An object that can optionally include information about the error.
type ModelError struct {
	// A detailed error message.
	Msg string `json:"msg,omitempty"`
	// The integer representing the HTTP status code (e.g. 200, 404).
	StatusCode int32 `json:"status_code,omitempty"`
}
