/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccessMethod struct {
	// Type of the access method.
	Type_ string `json:"type"`

	AccessUrl *AllOfAccessMethodAccessUrl `json:"access_url,omitempty"`
	// An arbitrary string to be passed to the `/access` method to get an `AccessURL`. This string must be unique within the scope of a single object. Note that at least one of `access_url` and `access_id` must be provided.
	AccessId string `json:"access_id,omitempty"`
	// Name of the cloud service provider that the object belongs to. If the cloud service is Amazon Web Services, Google Cloud Platform or Azure the values should be `aws`, `gcp`, or `azure` respectively.
	Cloud string `json:"cloud,omitempty"`
	// Name of the region in the cloud service provider that the object belongs to.
	Region string `json:"region,omitempty"`
	// Availablity of file in the cloud. This label defines if this file is immediately accessible via DRS. Any delay or requirement of thawing mechanism if the file is in offline/archival storage is classified as false, meaning it is unavailable.
	Available bool `json:"available,omitempty"`

	Authorizations *AllOfAccessMethodAuthorizations `json:"authorizations,omitempty"`
}
