/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The object that contains the DRS object IDs array
type BulkObjectId struct {
	// the encoded JWT GA4GH Passport that contains embedded Visas.  The overall JWT is signed as are the individual Passport Visas.
	Passports []string `json:"passports,omitempty"`
	// An array of ObjectIDs.
	BulkObjectIds []string `json:"bulk_object_ids,omitempty"`
}
