/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The object that contains object_id/access_id tuples
type BulkObjectAccessId struct {

	Passports []string `json:"passports,omitempty"`

	BulkObjectAccessIds []BulkObjectAccessIdBulkObjectAccessIds `json:"bulk_object_access_ids,omitempty"`
}
