/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Summary *Summary `json:"summary,omitempty"`

	UnresolvedDrsObjects *[]UnresolvedInner `json:"unresolved_drs_objects,omitempty"`

	ResolvedDrsObject []DrsObject `json:"resolved_drs_object,omitempty"`
}
