/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Authorizations struct {

	DrsObjectId string `json:"drs_object_id,omitempty"`
	// An Optional list of support authorization types. More than one can be supported and tried in sequence. Defaults to `None` if empty or missing.
	SupportedTypes []string `json:"supported_types,omitempty"`
	// If authorizations contain `PassportAuth` this is a required list of visa issuers (as found in a visa's `iss` claim) that may authorize access to this object. The caller must only provide passports that contain visas from this list. It is strongly recommended that the caller validate that it is appropriate to send the requested passport/visa to the DRS server to mitigate attacks by malicious DRS servers requesting credentials they should not have.
	PassportAuthIssuers []string `json:"passport_auth_issuers,omitempty"`
	// If authorizations contain `BearerAuth` this is an optional list of issuers that may authorize access to this object. The caller must provide a token from one of these issuers. If this is empty or missing it assumed the caller knows which token to send via other means. It is strongly recommended that the caller validate that it is appropriate to send the requested token to the DRS server to mitigate attacks by malicious DRS servers requesting credentials they should not have.
	BearerAuthIssuers []string `json:"bearer_auth_issuers,omitempty"`
}
