/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

import "net/http"

func GetServiceInfo(w http.ResponseWriter, r *http.Request) {
	sampler := GetDefaultServiceInfoSampler()
	if sampler == nil || sampler.Snapshot() == nil {
		writeJSONError(w, http.StatusServiceUnavailable, "service info sampler is not initialized")
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(sampler.Snapshot().ServiceInfoJSON)
}
