/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

import (
	"encoding/json"
	"fmt"
	"net/http"
	neturl "net/url"
	"strings"
	"time"

	irodsfs "github.com/cyverse/go-irodsclient/fs"
	"github.com/cyverse/go-irodsclient/irods/types"
	"github.com/gorilla/mux"
	extension_irodsuri "github.com/michael-conway/go-irodsclient-extensions/irodsuri"
	extmetadata "github.com/michael-conway/go-irodsclient-extensions/metadata"
	extmetadatairodsfs "github.com/michael-conway/go-irodsclient-extensions/metadata/irodsfs"
	extension_tickets "github.com/michael-conway/go-irodsclient-extensions/tickets"
	drs_support "github.com/michael-conway/irods-go-drs/drs-support"
)

type RouteFileSystem interface {
	drs_support.IRODSFilesystem
	drs_support.EntryMetadataQuerier
	CreateTicket(ticketName string, ticketType types.TicketType, path string) error
	ModifyTicketUseLimit(ticketName string, uses int64) error
	ModifyTicketExpirationTime(ticketName string, expirationTime time.Time) error
	DeleteTicket(ticketName string) error
	Release()
}

const compoundManifestHTTPSAccessID = "irods-compound-https"

type routeFileSystem struct {
	*irodsfs.FileSystem
}

func (f *routeFileSystem) QueryMetadataEntries(query extmetadata.EntryQuery) (extmetadata.EntryQueryResult, error) {
	return extmetadatairodsfs.NewAdapter(f.FileSystem).QueryEntries(query)
}

var createRouteFileSystem = func(account *types.IRODSAccount, applicationName string) (RouteFileSystem, error) {
	filesystem, err := irodsfs.NewFileSystemWithDefault(account, applicationName)
	if err != nil {
		return nil, err
	}
	return &routeFileSystem{FileSystem: filesystem}, nil
}

var createAdminRouteFileSystem = func(drsConfig *drs_support.DrsConfig, applicationName string) (RouteFileSystem, error) {
	if drsConfig == nil {
		return nil, fmt.Errorf("missing DRS config")
	}

	account := drsConfig.ToIrodsAccount()
	return createRouteFileSystem(&account, applicationName)
}

var readRouteDrsConfig = func() (*drs_support.DrsConfig, error) {
	return readDrsConfigNoPanic(drs_support.DefaultConfigName, drs_support.DefaultConfigType, nil)
}

func writeRouteFileSystemError(w http.ResponseWriter, r *http.Request, err error) {
	status := routeErrorStatus(err)
	message := "failed to connect to iRODS"
	if status == http.StatusUnauthorized {
		message = "iRODS authentication failed"
	} else if status == http.StatusForbidden {
		message = "iRODS authorization failed"
	}
	writeLoggedJSONError(w, r, status, message, "failed to create iRODS filesystem", err)
}

func routeErrorStatus(err error) int {
	if isIRODSAuthFailure(err) {
		return http.StatusUnauthorized
	}
	if isIRODSAuthorizationFailure(err) {
		return http.StatusForbidden
	}
	if err == nil {
		return http.StatusInternalServerError
	}

	message := err.Error()
	if strings.Contains(message, "not found") {
		return http.StatusNotFound
	}
	if strings.Contains(message, "required") {
		return http.StatusBadRequest
	}
	return http.StatusInternalServerError
}

func routeOperationClientMessage(status int, fallback string) string {
	switch status {
	case http.StatusUnauthorized:
		return "iRODS authentication failed"
	case http.StatusForbidden:
		return "iRODS authorization failed"
	case http.StatusNotFound:
		return "DRS object not found"
	case http.StatusBadRequest:
		return "invalid request"
	case http.StatusInternalServerError:
		return "internal server error"
	default:
		return fallback
	}
}

func writeLoggedJSONError(w http.ResponseWriter, r *http.Request, status int, message string, logMessage string, err error, args ...any) {
	logArgs := []any{
		"status", status,
		"method", "",
		"path", "",
	}
	if r != nil {
		logArgs[3] = r.Method
		logArgs[5] = r.URL.Path
	}
	if err != nil {
		logArgs = append(logArgs, "error", err.Error())
	}
	logArgs = append(logArgs, args...)
	requestLogger.Error(logMessage, logArgs...)
	writeJSONError(w, status, message)
}

func isIRODSAuthorizationFailure(err error) bool {
	if err == nil {
		return false
	}

	message := strings.ToLower(err.Error())
	for _, marker := range []string{
		"cat_no_access_permission",
		"cat_insufficient_privilege_level",
		"permission denied",
		"authorization error",
	} {
		if strings.Contains(message, marker) {
			return true
		}
	}
	return false
}

func isIRODSAuthFailure(err error) bool {
	if types.IsAuthError(err) {
		return true
	}

	message := strings.ToLower(err.Error())
	for _, marker := range []string{
		"authentication error",
		"cat_invalid_authentication",
		"pam_auth_password_failed",
		"remote_server_authentication_failure",
	} {
		if strings.Contains(message, marker) {
			return true
		}
	}
	return false
}

func GetAccessURL(w http.ResponseWriter, r *http.Request) {
	serviceContext, ok := DrsServiceContextFromContext(r.Context())
	if !ok || serviceContext == nil {
		writeJSONError(w, http.StatusInternalServerError, "missing DRS service context")
		return
	}

	vars := mux.Vars(r)
	objectID := strings.TrimSpace(vars["object_id"])
	if objectID == "" {
		writeJSONError(w, http.StatusBadRequest, "missing object_id")
		return
	}

	accessID := strings.TrimSpace(vars["access_id"])
	if accessID == "" {
		writeJSONError(w, http.StatusBadRequest, "missing access_id")
		return
	}
	if accessID != compoundManifestHTTPSAccessID {
		if err := validateConfiguredHTTPSProvider(serviceContext.DrsConfig); err != nil {
			writeLoggedJSONError(w, r, http.StatusNotImplemented, "https access provider is not supported in this deployment", "https access provider is not supported", err)
			return
		}
	}

	filesystem, err := createRouteFileSystem(serviceContext.IrodsAccount, "irods-go-drs-get-access-url")
	if err != nil {
		writeRouteFileSystemError(w, r, err)
		return
	}
	defer filesystem.Release()

	object, err := drs_support.GetDrsObjectByID(filesystem, filesystem, objectID)
	if err != nil {
		status := routeErrorStatus(err)
		writeLoggedJSONError(w, r, status, routeOperationClientMessage(status, "failed to resolve DRS object"), "failed to resolve DRS object", err, "object_id", objectID)
		return
	}

	response, status, err := accessURLForObject(filesystem, serviceContext.DrsConfig, objectID, accessID, object)
	if err != nil {
		if status == http.StatusInternalServerError {
			status = routeErrorStatus(err)
		}
		clientMessage := err.Error()
		if status == http.StatusInternalServerError || status == http.StatusUnauthorized || status == http.StatusBadRequest || status == http.StatusNotFound {
			clientMessage = routeOperationClientMessage(status, "failed to resolve access URL")
		}
		writeLoggedJSONError(w, r, status, clientMessage, "failed to resolve access URL", err, "object_id", objectID, "access_id", accessID)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(response)
}

func accessURLForObject(filesystem RouteFileSystem, drsConfig *drs_support.DrsConfig, objectID string, accessID string, object *drs_support.InternalDrsObject) (*AccessUrl, int, error) {
	if filesystem == nil {
		return nil, http.StatusInternalServerError, fmt.Errorf("missing iRODS filesystem")
	}
	if drsConfig == nil {
		return nil, http.StatusInternalServerError, fmt.Errorf("missing DRS config")
	}
	if object == nil {
		return nil, http.StatusInternalServerError, fmt.Errorf("missing DRS object")
	}

	switch strings.TrimSpace(accessID) {
	case compoundManifestHTTPSAccessID:
		if !object.IsManifest {
			return nil, http.StatusNotFound, fmt.Errorf("access id %q not found for object %q", accessID, objectID)
		}
		url, err := buildPublicAbsoluteURL(drsConfig, "/ga4gh/drs/v1/ext/compound/"+neturl.PathEscape(strings.TrimSpace(objectID)))
		if err != nil {
			return nil, http.StatusInternalServerError, fmt.Errorf("build compound manifest access URL for object %q: %w", objectID, err)
		}
		return &AccessUrl{Url: url}, http.StatusOK, nil
	case "irods":
		return buildIRODSAccessURL(filesystem, drsConfig, objectID, object)
	default:
		parsedAccessID, ok := drs_support.ParseHTTPSAccessID(accessID)
		if ok {
			return buildHTTPSProviderAccessURL(filesystem, drsConfig, objectID, object, parsedAccessID)
		}
		if existingType, found := accessMethodTypeByAccessID(drs_support.BuildAccessMethodsWithFilesystem(drsConfig, object, filesystem), accessID); found {
			return nil, http.StatusNotImplemented, fmt.Errorf("access id %q resolves to access method type %q, which is not supported by /access in this deployment", accessID, existingType)
		}
		return nil, http.StatusNotFound, fmt.Errorf("access id %q not found for object %q", accessID, objectID)
	}
}

func accessMethodTypeByAccessID(methods []drs_support.DrsAccessMethod, accessID string) (string, bool) {
	accessID = strings.TrimSpace(accessID)
	if accessID == "" || len(methods) == 0 {
		return "", false
	}

	for _, method := range methods {
		if strings.TrimSpace(method.AccessID) != accessID {
			continue
		}

		methodType := strings.TrimSpace(method.Type)
		if methodType == "" {
			methodType = "unknown"
		}
		return methodType, true
	}

	return "", false
}

func buildHTTPSProviderAccessURL(filesystem RouteFileSystem, drsConfig *drs_support.DrsConfig, objectID string, object *drs_support.InternalDrsObject, parsedAccessID drs_support.ParsedHTTPSAccessID) (*AccessUrl, int, error) {
	if !drsConfig.HttpsAccessMethodSupported {
		return nil, http.StatusNotImplemented, fmt.Errorf("https access method is not enabled")
	}
	configuredProvider := drs_support.EffectiveHTTPSAccessProvider(drsConfig.HttpsAccessImplementation)
	if !drs_support.IsSupportedHTTPSAccessProvider(configuredProvider) {
		return nil, http.StatusNotImplemented, fmt.Errorf("unsupported https access provider %q", strings.TrimSpace(drsConfig.HttpsAccessImplementation))
	}
	if parsedAccessID.Provider != configuredProvider {
		return nil, http.StatusNotFound, fmt.Errorf("access id provider %q does not match configured https provider %q", parsedAccessID.Provider, configuredProvider)
	}

	preferredHost := ""
	affinityResource := strings.TrimSpace(parsedAccessID.Resource)
	if affinityResource == "" {
		// Backward compatibility: default provider access IDs (without explicit
		// resource suffix) still resolve through resource affinity using the
		// object's primary replica resource.
		affinityResource = primaryReplicaResourceForAccess(object)
	}
	if affinityResource != "" {
		preferredHost = drs_support.ResolveAffinityHostForResource(drsConfig, affinityResource)
	}

	baseURL := drs_support.ResolveHTTPSAccessBaseURL(drsConfig.HttpsAccessMethodBaseURL, preferredHost)
	if baseURL == "" {
		return nil, http.StatusInternalServerError, fmt.Errorf("https access method base URL is not configured")
	}

	url := baseURL + neturl.QueryEscape(strings.TrimSpace(object.AbsolutePath))
	headers := []string{}

	if drsConfig.HttpsAccessUseTicket {
		ticketID, bearerToken, err := extension_tickets.CreateAnonymousDataObjectBearerToken(
			filesystem,
			object.AbsolutePath,
			int64(drsConfig.DefaultTicketUseLimit),
			drsConfig.DefaultTicketLifetimeMinutes,
		)
		if err != nil {
			return nil, http.StatusInternalServerError, fmt.Errorf("create access ticket for object %q: %w", objectID, err)
		}
		if strings.TrimSpace(ticketID) == "" {
			return nil, http.StatusInternalServerError, fmt.Errorf("created empty ticket id for object %q", objectID)
		}
		headers = append(headers, "Authorization: Bearer "+bearerToken)
	}

	return &AccessUrl{
		Url:     url,
		Headers: headers,
	}, http.StatusOK, nil
}

func primaryReplicaResourceForAccess(object *drs_support.InternalDrsObject) string {
	if object == nil {
		return ""
	}

	for _, replica := range object.Replicas {
		resourceName := strings.TrimSpace(replica.ResourceName)
		if resourceName != "" {
			return resourceName
		}
	}

	return strings.TrimSpace(object.ResourceName)
}

func buildIRODSAccessURL(filesystem RouteFileSystem, drsConfig *drs_support.DrsConfig, objectID string, object *drs_support.InternalDrsObject) (*AccessUrl, int, error) {
	if !drsConfig.IrodsAccessMethodSupported {
		return nil, http.StatusNotImplemented, fmt.Errorf("irods access method is not enabled")
	}

	host := strings.TrimSpace(drsConfig.IRODSAccessHost)
	if host == "" {
		host = strings.TrimSpace(drsConfig.IrodsHost)
	}
	if host == "" {
		if account := filesystem.GetAccount(); account != nil {
			host = strings.TrimSpace(account.Host)
		}
	}

	port := drsConfig.IRODSAccessPort
	if port == 0 {
		port = drsConfig.IrodsPort
	}
	if port <= 0 {
		if account := filesystem.GetAccount(); account != nil {
			port = account.Port
		}
	}

	zone := strings.TrimSpace(object.IrodsZone)
	if zone == "" {
		zone = strings.TrimSpace(drsConfig.IrodsZone)
	}

	if host == "" || port <= 0 {
		return nil, http.StatusInternalServerError, fmt.Errorf("irods access host and port must be configured")
	}
	if zone == "" {
		return nil, http.StatusInternalServerError, fmt.Errorf("irods zone must be configured for object %q", objectID)
	}
	if strings.TrimSpace(object.AbsolutePath) == "" {
		return nil, http.StatusInternalServerError, fmt.Errorf("irods absolute path is missing for object %q", objectID)
	}

	ticketID, _, err := extension_tickets.CreateAnonymousDataObjectBearerToken(
		filesystem,
		object.AbsolutePath,
		int64(drsConfig.DefaultTicketUseLimit),
		drsConfig.DefaultTicketLifetimeMinutes,
	)
	if err != nil {
		return nil, http.StatusInternalServerError, fmt.Errorf("create access ticket for object %q: %w", objectID, err)
	}
	if strings.TrimSpace(ticketID) == "" {
		return nil, http.StatusInternalServerError, fmt.Errorf("created empty ticket id for object %q", objectID)
	}

	uri, err := extension_irodsuri.BuildWithTicket(host, port, &extension_irodsuri.UserInfo{
		UserName: "anonymous",
		Zone:     zone,
	}, object.AbsolutePath, ticketID)
	if err != nil {
		return nil, http.StatusInternalServerError, fmt.Errorf("build irods access URI for object %q: %w", objectID, err)
	}

	return &AccessUrl{
		Url: uri.String(),
	}, http.StatusOK, nil
}

func GetBulkAccessURL(w http.ResponseWriter, r *http.Request) {
	writeUnsupportedOperation(w, "POST /ga4gh/drs/v1/objects/access")
}

func GetBulkObjects(w http.ResponseWriter, r *http.Request) {
	writeUnsupportedOperation(w, "POST /ga4gh/drs/v1/objects")
}

func GetObject(w http.ResponseWriter, r *http.Request) {
	serviceContext, ok := DrsServiceContextFromContext(r.Context())
	if !ok || serviceContext == nil {
		writeJSONError(w, http.StatusInternalServerError, "missing DRS service context")
		return
	}

	vars := mux.Vars(r)
	objectID := strings.TrimSpace(vars["object_id"])
	if objectID == "" {
		writeJSONError(w, http.StatusBadRequest, "missing object_id")
		return
	}

	filesystem, err := createRouteFileSystem(serviceContext.IrodsAccount, "irods-go-drs-get-object")
	if err != nil {
		writeRouteFileSystemError(w, r, err)
		return
	}
	defer filesystem.Release()

	object, err := drs_support.GetDrsObjectByID(filesystem, filesystem, objectID)
	if err != nil {
		status := routeErrorStatus(err)
		writeLoggedJSONError(w, r, status, routeOperationClientMessage(status, "failed to resolve DRS object"), "failed to resolve DRS object", err, "object_id", objectID)
		return
	}
	if !object.IsManifest {
		if err := validateConfiguredHTTPSProvider(serviceContext.DrsConfig); err != nil {
			writeLoggedJSONError(w, r, http.StatusNotImplemented, "https access provider is not supported in this deployment", "https access provider is not supported", err)
			return
		}
	}

	expand := strings.EqualFold(strings.TrimSpace(r.URL.Query().Get("expand")), "true")
	response, err := drsObjectFromInternal(r, object, expand, filesystem)
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to build DRS object response", "failed to build DRS object response", err, "object_id", objectID)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(response)
}

func GetCompoundManifestExt(w http.ResponseWriter, r *http.Request) {
	serviceContext, ok := DrsServiceContextFromContext(r.Context())
	if !ok || serviceContext == nil {
		writeJSONError(w, http.StatusInternalServerError, "missing DRS service context")
		return
	}

	vars := mux.Vars(r)
	objectID := strings.TrimSpace(vars["object_id"])
	if objectID == "" {
		writeJSONError(w, http.StatusBadRequest, "missing object_id")
		return
	}

	filesystem, err := createRouteFileSystem(serviceContext.IrodsAccount, "irods-go-drs-get-compound-manifest-ext")
	if err != nil {
		writeRouteFileSystemError(w, r, err)
		return
	}
	defer filesystem.Release()

	object, err := drs_support.GetDrsObjectByID(filesystem, filesystem, objectID)
	if err != nil {
		status := routeErrorStatus(err)
		writeLoggedJSONError(w, r, status, routeOperationClientMessage(status, "failed to resolve DRS object"), "failed to resolve DRS object", err, "object_id", objectID)
		return
	}

	if !object.IsManifest {
		writeJSONError(w, http.StatusBadRequest, fmt.Sprintf("DRS object %q is not a compound object", objectID))
		return
	}

	manifest, err := drs_support.BuildCompoundRuntimeManifest(filesystem, object.AbsolutePath)
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to build compound manifest", "failed to build compound manifest", err, "object_id", objectID)
		return
	}
	manifestJSON, err := drs_support.MarshalCompoundRuntimeManifest(manifest)
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to serialize compound manifest", "failed to serialize compound manifest", err, "object_id", objectID)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(manifestJSON)
}

func OptionsBulkObject(w http.ResponseWriter, r *http.Request) {
	drsConfig, err := readRouteDrsConfig()
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to read DRS configuration", "failed to read DRS configuration", err)
		return
	}

	if err := validateConfiguredHTTPSProvider(drsConfig); err != nil {
		writeLoggedJSONError(w, r, http.StatusNotImplemented, "https access provider is not supported in this deployment", "https access provider is not supported", err)
		return
	}

	var request BulkObjectIdNoPassport
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		writeLoggedJSONError(w, r, http.StatusBadRequest, "invalid request body", "invalid request body", err)
		return
	}

	objectIDs := normalizedBulkObjectIDs(request.BulkObjectIds)
	if len(objectIDs) == 0 {
		writeJSONError(w, http.StatusBadRequest, "bulk_object_ids must contain at least one object id")
		return
	}

	filesystem, err := createAdminRouteFileSystem(drsConfig, "irods-go-drs-options-bulk-object")
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to connect to iRODS", "failed to create iRODS filesystem", err)
		return
	}
	defer filesystem.Release()

	response, err := bulkAuthorizationsFromIDs(filesystem, drsConfig, objectIDs)
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to resolve DRS object authorizations", "failed to resolve DRS object authorizations", err)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(response)
}

func OptionsObject(w http.ResponseWriter, r *http.Request) {
	drsConfig, err := readRouteDrsConfig()
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to read DRS configuration", "failed to read DRS configuration", err)
		return
	}

	if err := validateConfiguredHTTPSProvider(drsConfig); err != nil {
		writeLoggedJSONError(w, r, http.StatusNotImplemented, "https access provider is not supported in this deployment", "https access provider is not supported", err)
		return
	}

	vars := mux.Vars(r)
	objectID := strings.TrimSpace(vars["object_id"])
	if objectID == "" {
		writeJSONError(w, http.StatusBadRequest, "missing object_id")
		return
	}

	filesystem, err := createAdminRouteFileSystem(drsConfig, "irods-go-drs-options-object")
	if err != nil {
		writeLoggedJSONError(w, r, http.StatusInternalServerError, "failed to connect to iRODS", "failed to create iRODS filesystem", err)
		return
	}
	defer filesystem.Release()

	if _, err := drs_support.GetDrsObjectByID(filesystem, filesystem, objectID); err != nil {
		status := http.StatusInternalServerError
		if strings.Contains(err.Error(), "not found") {
			status = http.StatusNotFound
		} else if strings.Contains(err.Error(), "required") {
			status = http.StatusBadRequest
		}

		writeLoggedJSONError(w, r, status, routeOperationClientMessage(status, "failed to resolve DRS object"), "failed to resolve DRS object", err, "object_id", objectID)
		return
	}

	response := authorizationsFromConfig(objectID, drsConfig)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(response)
}

func PostAccessURL(w http.ResponseWriter, r *http.Request) {
	writeUnsupportedOperation(w, "POST /ga4gh/drs/v1/objects/{object_id}/access/{access_id}")
}

func PostObject(w http.ResponseWriter, r *http.Request) {
	writeUnsupportedOperation(w, "POST /ga4gh/drs/v1/objects/{object_id}")
}

func writeUnsupportedOperation(w http.ResponseWriter, endpoint string) {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		endpoint = "requested endpoint"
	}

	writeJSONError(
		w,
		http.StatusNotImplemented,
		fmt.Sprintf("%s is not supported in this deployment", endpoint),
	)
}

func drsObjectFromInternal(r *http.Request, object *drs_support.InternalDrsObject, expand bool, filesystem drs_support.IRODSFilesystem) (DrsObject, error) {
	var accessMethods []AccessMethod
	var drsConfig *drs_support.DrsConfig
	if serviceContext, ok := DrsServiceContextFromContext(r.Context()); ok && serviceContext != nil {
		drsConfig = serviceContext.DrsConfig
		if object != nil && object.IsManifest {
			accessMethod, err := buildCompoundManifestAccessMethod(serviceContext.DrsConfig, object)
			if err != nil {
				return DrsObject{}, err
			}
			accessMethods = []AccessMethod{accessMethod}
		} else {
			accessMethods = accessMethodsFromInternal(drs_support.BuildAccessMethodsWithFilesystem(serviceContext.DrsConfig, object, filesystem))
		}
	}

	aliases := append([]string(nil), object.Aliases...)
	if irodsURIAlias := buildAnonymousIRODSAliasURI(filesystem, object); irodsURIAlias != "" {
		alreadyPresent := false
		for _, alias := range aliases {
			if strings.EqualFold(strings.TrimSpace(alias), strings.TrimSpace(irodsURIAlias)) {
				alreadyPresent = true
				break
			}
		}
		if !alreadyPresent {
			aliases = append(aliases, irodsURIAlias)
		}
	}

	selfURI, err := buildSelfURI(drsConfig, object.Id)
	if err != nil {
		return DrsObject{}, fmt.Errorf("build self_uri for object %q: %w", strings.TrimSpace(object.Id), err)
	}

	response := DrsObject{
		Id:            object.Id,
		Name:          object.AbsolutePath,
		SelfUri:       selfURI,
		Size:          object.Size,
		CreatedTime:   object.CreatedTime,
		UpdatedTime:   object.UpdatedTime,
		Version:       object.Version,
		MimeType:      object.MimeType,
		AccessMethods: accessMethods,
		Description:   object.Description,
		Aliases:       aliases,
	}

	if object.Checksum != nil && object.Checksum.Value != "" {
		response.Checksums = []Checksum{{
			Checksum: object.Checksum.Value,
			Type_:    object.Checksum.Type,
		}}
	} else {
		response.Checksums = []Checksum{}
	}

	if expand && len(object.Contents) > 0 {
		response.Contents = make([]ContentsObject, 0, len(object.Contents))
		for _, entry := range object.Contents {
			drsURIs, err := buildContentsDrsURIs(drsConfig, entry.ID)
			if err != nil {
				return DrsObject{}, fmt.Errorf("build content drs_uri for object %q: %w", strings.TrimSpace(entry.ID), err)
			}

			response.Contents = append(response.Contents, ContentsObject{
				Name:   entry.Name,
				Id:     entry.ID,
				DrsUri: drsURIs,
			})
		}
	}

	return response, nil
}

func buildAnonymousIRODSAliasURI(filesystem drs_support.IRODSFilesystem, object *drs_support.InternalDrsObject) string {
	if filesystem == nil || object == nil {
		return ""
	}

	absolutePath := strings.TrimSpace(object.AbsolutePath)
	if absolutePath == "" {
		return ""
	}

	account := filesystem.GetAccount()
	if account == nil {
		return ""
	}

	uri, err := extension_irodsuri.BuildForAccountWithoutUserInfo(account, absolutePath)
	if err != nil || uri == nil {
		return ""
	}
	return uri.String()
}

func accessMethodsFromInternal(methods []drs_support.DrsAccessMethod) []AccessMethod {
	if len(methods) == 0 {
		return nil
	}

	response := make([]AccessMethod, 0, len(methods))
	for _, method := range methods {
		accessMethod := AccessMethod{
			Type_:     method.Type,
			AccessId:  method.AccessID,
			Cloud:     method.Cloud,
			Region:    method.Region,
			Available: method.Available,
		}

		if method.URL != "" {
			accessMethod.AccessUrl = &AllOfAccessMethodAccessUrl{
				Url: method.URL,
			}
		}

		if len(method.SupportedAuthTypes) > 0 || len(method.BearerAuthIssuers) > 0 {
			accessMethod.Authorizations = &AllOfAccessMethodAuthorizations{
				SupportedTypes:    append([]string(nil), method.SupportedAuthTypes...),
				BearerAuthIssuers: append([]string(nil), method.BearerAuthIssuers...),
			}
		}

		response = append(response, accessMethod)
	}

	return response
}

func buildCompoundManifestAccessMethod(drsConfig *drs_support.DrsConfig, object *drs_support.InternalDrsObject) (AccessMethod, error) {
	region := ""
	zone := ""
	if object != nil {
		region = strings.TrimSpace(object.ResourceName)
		zone = strings.TrimSpace(object.IrodsZone)
	}
	issuers := []string{}
	if issuer := bearerAuthIssuerFromConfig(drsConfig); issuer != "" {
		issuers = append(issuers, issuer)
	}
	compoundPath := "/ga4gh/drs/v1/ext/compound/"
	if object != nil {
		compoundPath = compoundPath + neturl.PathEscape(strings.TrimSpace(object.Id))
	}

	compoundURL, err := buildPublicAbsoluteURL(drsConfig, compoundPath)
	if err != nil {
		return AccessMethod{}, fmt.Errorf("build compound manifest access_url: %w", err)
	}

	return AccessMethod{
		Type_:     "https",
		AccessUrl: &AllOfAccessMethodAccessUrl{Url: compoundURL},
		Cloud:     "irods:" + zone,
		Region:    region,
		Available: false,
		Authorizations: &AllOfAccessMethodAuthorizations{
			SupportedTypes:    []string{"BasicAuth", "BearerAuth"},
			BearerAuthIssuers: issuers,
		},
	}, nil
}

func buildSelfURI(drsConfig *drs_support.DrsConfig, objectID string) (string, error) {
	objectID = strings.TrimSpace(objectID)
	if objectID == "" {
		return "", fmt.Errorf("missing object id")
	}

	baseURL, err := publicBaseURLFromConfig(drsConfig)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("drs://%s/%s", baseURL.Host, objectID), nil
}

func buildPublicAbsoluteURL(drsConfig *drs_support.DrsConfig, targetPath string) (string, error) {
	targetPath = "/" + strings.TrimPrefix(strings.TrimSpace(targetPath), "/")
	if strings.TrimSpace(targetPath) == "/" {
		return "", fmt.Errorf("missing target path")
	}

	baseURL, err := publicBaseURLFromConfig(drsConfig)
	if err != nil {
		return "", err
	}

	resolvedTarget, err := neturl.Parse(targetPath)
	if err != nil {
		return "", fmt.Errorf("invalid target path %q: %w", targetPath, err)
	}
	if resolvedTarget.Scheme != "" || resolvedTarget.Host != "" {
		return "", fmt.Errorf("target path must be relative to configured public URL")
	}

	return baseURL.ResolveReference(resolvedTarget).String(), nil
}

func publicBaseURLFromConfig(drsConfig *drs_support.DrsConfig) (*neturl.URL, error) {
	if drsConfig == nil {
		return nil, fmt.Errorf("missing DRS config")
	}

	rawPublicURL := strings.TrimSpace(drsConfig.PublicURL)
	if rawPublicURL == "" {
		return nil, fmt.Errorf("PublicURL must be configured")
	}

	parsed, err := neturl.Parse(rawPublicURL)
	if err != nil {
		return nil, fmt.Errorf("invalid PublicURL %q: %w", rawPublicURL, err)
	}

	scheme := strings.ToLower(strings.TrimSpace(parsed.Scheme))
	if scheme != "http" && scheme != "https" {
		return nil, fmt.Errorf("PublicURL must use http or https scheme")
	}
	if strings.TrimSpace(parsed.Host) == "" {
		return nil, fmt.Errorf("PublicURL must include host")
	}
	if parsed.User != nil {
		return nil, fmt.Errorf("PublicURL must not include user info")
	}
	if strings.TrimSpace(parsed.RawQuery) != "" || strings.TrimSpace(parsed.Fragment) != "" {
		return nil, fmt.Errorf("PublicURL must not include query or fragment")
	}
	if path := strings.TrimSpace(parsed.Path); path != "" && path != "/" {
		return nil, fmt.Errorf("PublicURL must not include a path")
	}

	return &neturl.URL{
		Scheme: scheme,
		Host:   strings.TrimSpace(parsed.Host),
	}, nil
}

func buildContentsDrsURIs(drsConfig *drs_support.DrsConfig, objectID string) ([]string, error) {
	objectID = strings.TrimSpace(objectID)
	if objectID == "" {
		return nil, nil
	}

	selfURI, err := buildSelfURI(drsConfig, objectID)
	if err != nil {
		return nil, err
	}

	return []string{selfURI}, nil
}

func authorizationsFromConfig(objectID string, drsConfig *drs_support.DrsConfig) Authorizations {
	response := Authorizations{
		DrsObjectId:    strings.TrimSpace(objectID),
		SupportedTypes: []string{"BasicAuth", "BearerAuth"},
	}

	if issuer := bearerAuthIssuerFromConfig(drsConfig); issuer != "" {
		response.BearerAuthIssuers = []string{issuer}
	}

	return response
}

func bulkAuthorizationsFromIDs(filesystem RouteFileSystem, drsConfig *drs_support.DrsConfig, objectIDs []string) (*InlineResponse2002, error) {
	resolved := make([]Authorizations, 0, len(objectIDs))
	missingIDs := make([]string, 0)

	for _, objectID := range objectIDs {
		if _, err := drs_support.GetDrsObjectByID(filesystem, filesystem, objectID); err != nil {
			if strings.Contains(err.Error(), "not found") {
				missingIDs = append(missingIDs, objectID)
				continue
			}

			return nil, fmt.Errorf("resolve DRS object %q: %w", objectID, err)
		}

		resolved = append(resolved, authorizationsFromConfig(objectID, drsConfig))
	}

	response := &InlineResponse2002{
		Summary: &Summary{
			Requested:  int32(len(objectIDs)),
			Resolved:   int32(len(resolved)),
			Unresolved: int32(len(missingIDs)),
		},
		ResolvedDrsObject: resolved,
	}

	if len(missingIDs) > 0 {
		unresolved := []UnresolvedInner{{
			ErrorCode: http.StatusNotFound,
			ObjectIds: append([]string(nil), missingIDs...),
		}}
		response.UnresolvedDrsObjects = &unresolved
	}

	return response, nil
}

func normalizedBulkObjectIDs(objectIDs []string) []string {
	resolved := make([]string, 0, len(objectIDs))
	for _, objectID := range objectIDs {
		objectID = strings.TrimSpace(objectID)
		if objectID == "" {
			continue
		}
		resolved = append(resolved, objectID)
	}

	return resolved
}

func validateConfiguredHTTPSProvider(drsConfig *drs_support.DrsConfig) error {
	if drsConfig == nil || !drsConfig.HttpsAccessMethodSupported {
		return nil
	}

	switch drs_support.EffectiveHTTPSAccessProvider(drsConfig.HttpsAccessImplementation) {
	case drs_support.HTTPSProviderIRODSGoREST, drs_support.HTTPSProviderIRODSHTTPSAPI:
		return nil
	default:
		return fmt.Errorf("unsupported https access provider %q", drsConfig.HttpsAccessImplementation)
	}
}

func bearerAuthIssuerFromConfig(drsConfig *drs_support.DrsConfig) string {
	if drsConfig == nil {
		return ""
	}

	baseURL := strings.TrimRight(strings.TrimSpace(drsConfig.OidcUrl), "/")
	if baseURL == "" {
		return ""
	}

	realm := strings.TrimSpace(drsConfig.OidcRealm)
	if realm == "" {
		return baseURL
	}

	return baseURL + "/realms/" + neturl.PathEscape(realm)
}
