/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

type UnresolvedInner struct {
	ErrorCode int32 `json:"error_code,omitempty"`

	ObjectIds []string `json:"object_ids,omitempty"`
}
