/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

type BulkAccessUrl struct {
	DrsObjectId string `json:"drs_object_id,omitempty"`

	DrsAccessId string `json:"drs_access_id,omitempty"`
	// A fully resolvable URL that can be used to fetch the actual object bytes.
	Url string `json:"url"`
	// An optional list of headers to include in the HTTP request to `url`. These headers can be used to provide auth tokens required to fetch the object bytes.
	Headers []string `json:"headers,omitempty"`
}
