/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

type DrsServiceDrs struct {
	// The max length the bulk request endpoints can handle (>= 1) before generating a 413 error e.g. how long can the arrays bulk_object_ids and bulk_object_access_ids be for this server.
	MaxBulkRequestLength int32 `json:"maxBulkRequestLength"`
	// The total number of objects in this DRS service.
	ObjectCount int32 `json:"objectCount,omitempty"`
	// The total size of all objects in this DRS service in bytes.  As a general best practice, file bytes are counted for each unique file and not cloud mirrors or other redundant copies.
	TotalObjectSize int32 `json:"totalObjectSize,omitempty"`
}
