/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name         string
	Method       string
	Pattern      string
	HandlerFunc  http.HandlerFunc
	RequiresAuth bool
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	authMiddleware := NewDefaultRouteAuthMiddleware()
	serviceContextMiddleware := NewDefaultRouteServiceContextMiddleware()

	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		if route.RequiresAuth && serviceContextMiddleware != nil {
			handler = serviceContextMiddleware(handler)
		}
		if route.RequiresAuth && authMiddleware != nil {
			handler = authMiddleware(handler)
		}
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/ga4gh/drs/v1/",
		Index,
		false,
	},
	Route{
		"GetOpenAPISpec",
		"GET",
		"/openapi.yaml",
		GetOpenAPISpec,
		false,
	},
	Route{
		"GetSwaggerUI",
		"GET",
		"/swagger",
		GetSwaggerUI,
		false,
	},

	Route{
		"GetAccessURL",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
		GetAccessURL,
		true,
	},

	Route{
		"GetBulkAccessURL",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/access",
		GetBulkAccessURL,
		true,
	},

	Route{
		"GetBulkObjects",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects",
		GetBulkObjects,
		true,
	},

	Route{
		"GetObject",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/objects/{object_id}",
		GetObject,
		true,
	},

	Route{
		"OptionsBulkObject",
		strings.ToUpper("Options"),
		"/ga4gh/drs/v1/objects",
		OptionsBulkObject,
		false,
	},

	Route{
		"OptionsObject",
		strings.ToUpper("Options"),
		"/ga4gh/drs/v1/objects/{object_id}",
		OptionsObject,
		false,
	},

	Route{
		"PostAccessURL",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
		PostAccessURL,
		true,
	},

	Route{
		"PostObject",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/{object_id}",
		PostObject,
		true,
	},

	Route{
		"GetServiceInfo",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/service-info",
		GetServiceInfo,
		false,
	},
}
