/*
 * Data Repository Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package internal

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/ga4gh/drs/v1/",
		Index,
	},

	Route{
		"GetAccessURL",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
		GetAccessURL,
	},

	Route{
		"GetBulkAccessURL",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/access",
		GetBulkAccessURL,
	},

	Route{
		"GetBulkObjects",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects",
		GetBulkObjects,
	},

	Route{
		"GetObject",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/objects/{object_id}",
		GetObject,
	},

	Route{
		"OptionsBulkObject",
		strings.ToUpper("Options"),
		"/ga4gh/drs/v1/objects",
		OptionsBulkObject,
	},

	Route{
		"OptionsObject",
		strings.ToUpper("Options"),
		"/ga4gh/drs/v1/objects/{object_id}",
		OptionsObject,
	},

	Route{
		"PostAccessURL",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
		PostAccessURL,
	},

	Route{
		"PostObject",
		strings.ToUpper("Post"),
		"/ga4gh/drs/v1/objects/{object_id}",
		PostObject,
	},

	Route{
		"GetServiceInfo",
		strings.ToUpper("Get"),
		"/ga4gh/drs/v1/service-info",
		GetServiceInfo,
	},
}
